#!/usr/bin/env bash

cache_dir="$HOME/.cache/eww/gcal"
cache_gcal_event=${cache_dir}/gcal-event
cache_gcal_time=${cache_dir}/gcal-time


update_cache() {
    if [[ ! -d "$cache_dir" ]]; then
        mkdir -p ${cache_dir}
    fi

    agenda=$(gcalcli --nocolor agenda "$(date)" | head -n 2 | tail -n 1)
    time=$(echo $agenda | awk '{print $1,$2,$3,$4}')
    event=$(echo $agenda | awk '{for(i=7; i<=NF; ++i) printf "%s ", $i; print ""}')

    # echo $time > $cache_gcal_time
    # echo $event > $cache_gcal_event
    # echo "$time, $event" 

	# notify-send "eww" 'Updated gcal!'
    return
}


if [[ "$1" == "--update-cache" ]]; then
	update_cache
elif [[ "$1" == "--event" ]]; then
	tail -F ${cache_gcal_event}
elif [[ "$1" == "--time" ]]; then
	tail -F ${cache_gcal_time}
fi