#!/bin/bash

if [[ $1 == "picker" ]]; then
    cd $HOME
    eww close-all
    $HOME/.scripts/color-picker
elif [[ $1 == "powermenu" ]]; then
    cd $HOME
    eww close-all
    $HOME/.config/rofi/powermenu/powermenu.sh
elif [[ $1 == "explorer" ]]; then
    cd $HOME
    eww close-all
    spacefm
elif [[ $1 == "settings" ]]; then
    cd $HOME
    eww close-all
    code ~/.config
elif [[ $1 == "volume" ]]; then
    cd $HOME
    eww close-all
    pavucontrol
elif [[ $1 == "display" ]]; then
    cd $HOME
    eww close-all
    xfce4-display-settings
elif [[ $1 == "power" ]]; then
    cd $HOME
    eww close-all
    xfce4-power-manager --restart
elif [[ $1 == "exit" ]]; then
    eww close-all
elif [[ $1 == "wifi" ]]; then
    cd $HOME
    eww close-all
    nm-connection-editor
elif [[ $1 == "gcal" ]]; then
    cd $HOME
    eww close-all
    alacritty --hold -e gcalcli agenda
elif [[ $1 == "weather" ]]; then
    cd $HOME
    eww close-all
    xdg-open 'https://www.yr.no/nb/v%C3%A6rvarsel/daglig-tabell/1-2797761/Norge/Innlandet/Lillehammer/J%C3%B8rstadmoen'
fi 
elif [[ $1 == "weather" ]]; then
    cd $HOME
    eww close-all
    blueberry
fi 